version: "2"
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
  settings:
    gosec:
      excludes:
        - G104
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-naming
        - name: error-strings
        - name: error-return
        - name: errorf
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: var-declaration
        - name: var-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - errcheck
          - gosec
        path: integration/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
